export const SET_NAME = 'TWOSEVENZERO/CANDIDATE/SET_NAME';
export const SET_PARTY = 'TWOSEVENZERO/CANDIDATE/SET_PARTY';
export const INCREASE_ELECTORAL_VOTES = 'TWOSEVENZERO/CANDIDATE/INCREASE_ELECTORAL_VOTES';
export const INCREASE_OPPONENT_ELECTORAL_VOTES = 'TWOSEVENZERO/CANDIDATE/INCREASE_OPPONENT_ELECTORAL_VOTES';
export const RESET_CANDIDACY = 'TWOSEVENZERO/CANDIDATE/RESET_CANDIDACY';