export const SET_VOTE_PERCENTAGE = 'TWO_SEVEN_ZERO/ELECTION/SET_VOTE_PERCENTAGE';
export const SET_STATE_ELECTION = 'TWO_SEVEN_ZERO/ELECTION/SET_STATE_ELECTION'
export const SET_OPPONENT_VOTE_PERCENTAGE = 'TWO_SEVEN_ZERO/ELECTION/SET_OPPONENT_VOTE_PERCENTAGE';
