export const RESET_MAP = 'TWOSEVENZERO/ELECTORAL_MAP/RESET_MAP';
export const WIN_DISTRICT = 'TWOSEVENZERO/ELECTORAL_MAP/WIN_DISTRICT';
export const INCREASE_SCORE = 'TWOSEVENZERO/ELECTORAL_MAP/INCREASE_SCORE';
export const COMPLETE_DISTRICT = 'TWOSEVENZERO/ELECTORAL_MAP/COMPLETE_DISTRICT';
export const INCREASE_OPPONENT_SCORE = 'TWOSEVENZERO/ELECTORAL_MAP/INCREASE_OPPONENT_SCORE';
