export const BACK = 'Navigation/BACK';
export const POP = 'TWOSEVENZERO/MAIN_NAVIGATION/POP';
export const PUSH = 'TWOSEVENZERO/MAIN_NAVIGATION/PUSH';
export const SET_ROOT = 'TWOSEVENZERO/MAIN_NAVIGATION/SET_ROOT';
